blank_issues_enabled: false
contact_links:
  - name: 💬 Questions or Discussions
    url: https://github.com/daviguides/keysentinel/discussions
    about: If you have questions, feedback, or want to discuss ideas, please open a discussion instead of an issue.